// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/poh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type POHHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count        int64          `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	LastHash     string         `protobuf:"bytes,2,opt,name=LastHash,proto3" json:"LastHash,omitempty"`
	Hash         string         `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Transactions []*Transaction `protobuf:"bytes,4,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
}

func (x *POHHash) Reset() {
	*x = POHHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poh_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POHHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POHHash) ProtoMessage() {}

func (x *POHHash) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poh_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POHHash.ProtoReflect.Descriptor instead.
func (*POHHash) Descriptor() ([]byte, []int) {
	return file_proto_poh_proto_rawDescGZIP(), []int{0}
}

func (x *POHHash) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *POHHash) GetLastHash() string {
	if x != nil {
		return x.LastHash
	}
	return ""
}

func (x *POHHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *POHHash) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type POHTick struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hashes []*POHHash `protobuf:"bytes,1,rep,name=Hashes,proto3" json:"Hashes,omitempty"`
	Count  int64      `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
}

func (x *POHTick) Reset() {
	*x = POHTick{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poh_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POHTick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POHTick) ProtoMessage() {}

func (x *POHTick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poh_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POHTick.ProtoReflect.Descriptor instead.
func (*POHTick) Descriptor() ([]byte, []int) {
	return file_proto_poh_proto_rawDescGZIP(), []int{1}
}

func (x *POHTick) GetHashes() []*POHHash {
	if x != nil {
		return x.Hashes
	}
	return nil
}

func (x *POHTick) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type POHBlock struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticks []*POHTick `protobuf:"bytes,1,rep,name=Ticks,proto3" json:"Ticks,omitempty"`
	Count int64      `protobuf:"varint,2,opt,name=Count,proto3" json:"Count,omitempty"`
	Type  string     `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	Hash  *POHHash   `protobuf:"bytes,4,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Votes []*POHVote `protobuf:"bytes,5,rep,name=Votes,proto3" json:"Votes,omitempty"`
}

func (x *POHBlock) Reset() {
	*x = POHBlock{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poh_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POHBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POHBlock) ProtoMessage() {}

func (x *POHBlock) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poh_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POHBlock.ProtoReflect.Descriptor instead.
func (*POHBlock) Descriptor() ([]byte, []int) {
	return file_proto_poh_proto_rawDescGZIP(), []int{2}
}

func (x *POHBlock) GetTicks() []*POHTick {
	if x != nil {
		return x.Ticks
	}
	return nil
}

func (x *POHBlock) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *POHBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *POHBlock) GetHash() *POHHash {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *POHBlock) GetVotes() []*POHVote {
	if x != nil {
		return x.Votes
	}
	return nil
}

type POHVote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash    string `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	Sign    string `protobuf:"bytes,3,opt,name=Sign,proto3" json:"Sign,omitempty"`
}

func (x *POHVote) Reset() {
	*x = POHVote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_poh_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *POHVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*POHVote) ProtoMessage() {}

func (x *POHVote) ProtoReflect() protoreflect.Message {
	mi := &file_proto_poh_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use POHVote.ProtoReflect.Descriptor instead.
func (*POHVote) Descriptor() ([]byte, []int) {
	return file_proto_poh_proto_rawDescGZIP(), []int{3}
}

func (x *POHVote) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *POHVote) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *POHVote) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

var File_proto_poh_proto protoreflect.FileDescriptor

var file_proto_poh_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x70, 0x6f, 0x68, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8d, 0x01, 0x0a, 0x07, 0x50, 0x4f, 0x48, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x3c, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x45, 0x0a, 0x07, 0x50, 0x4f, 0x48, 0x54, 0x69, 0x63, 0x6b, 0x12, 0x24, 0x0a, 0x06, 0x48, 0x61,
	0x73, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6f, 0x68,
	0x2e, 0x50, 0x4f, 0x48, 0x48, 0x61, 0x73, 0x68, 0x52, 0x06, 0x48, 0x61, 0x73, 0x68, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x08, 0x50, 0x4f, 0x48, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x22, 0x0a, 0x05, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6f, 0x68, 0x2e, 0x50, 0x4f, 0x48, 0x54, 0x69, 0x63, 0x6b,
	0x52, 0x05, 0x54, 0x69, 0x63, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x20, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x6f, 0x68, 0x2e, 0x50, 0x4f, 0x48, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x22, 0x0a, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6f, 0x68, 0x2e, 0x50, 0x4f, 0x48, 0x56, 0x6f, 0x74, 0x65,
	0x52, 0x05, 0x56, 0x6f, 0x74, 0x65, 0x73, 0x22, 0x4b, 0x0a, 0x07, 0x50, 0x4f, 0x48, 0x56, 0x6f,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x42, 0x08, 0x5a, 0x06, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_poh_proto_rawDescOnce sync.Once
	file_proto_poh_proto_rawDescData = file_proto_poh_proto_rawDesc
)

func file_proto_poh_proto_rawDescGZIP() []byte {
	file_proto_poh_proto_rawDescOnce.Do(func() {
		file_proto_poh_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_poh_proto_rawDescData)
	})
	return file_proto_poh_proto_rawDescData
}

var file_proto_poh_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_poh_proto_goTypes = []interface{}{
	(*POHHash)(nil),     // 0: poh.POHHash
	(*POHTick)(nil),     // 1: poh.POHTick
	(*POHBlock)(nil),    // 2: poh.POHBlock
	(*POHVote)(nil),     // 3: poh.POHVote
	(*Transaction)(nil), // 4: transaction.Transaction
}
var file_proto_poh_proto_depIdxs = []int32{
	4, // 0: poh.POHHash.Transactions:type_name -> transaction.Transaction
	0, // 1: poh.POHTick.Hashes:type_name -> poh.POHHash
	1, // 2: poh.POHBlock.Ticks:type_name -> poh.POHTick
	0, // 3: poh.POHBlock.Hash:type_name -> poh.POHHash
	3, // 4: poh.POHBlock.Votes:type_name -> poh.POHVote
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_poh_proto_init() }
func file_proto_poh_proto_init() {
	if File_proto_poh_proto != nil {
		return
	}
	file_proto_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_poh_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POHHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poh_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POHTick); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poh_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POHBlock); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_poh_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*POHVote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_poh_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_poh_proto_goTypes,
		DependencyIndexes: file_proto_poh_proto_depIdxs,
		MessageInfos:      file_proto_poh_proto_msgTypes,
	}.Build()
	File_proto_poh_proto = out.File
	file_proto_poh_proto_rawDesc = nil
	file_proto_poh_proto_goTypes = nil
	file_proto_poh_proto_depIdxs = nil
}
